version: 0.2

phases:
  install:
    commands:
   # Update apt and install dependencies for adding repos
      - apt-get update -y
      - apt-get install -y curl apt-transport-https gnupg

      # Add Kubernetes official apt repository
      - curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      - echo "deb https://apt.kubernetes.io/ kubernetes-stable main" | tee /etc/apt/sources.list.d/kubernetes.list

      # Update apt again to include the Kubernetes repo
      - apt-get update -y

      # Install required packages (AWS CLI, Docker, kubectl)
      - apt-get install -y awscli docker.io kubectl

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 344101797155.dkr.ecr.us-west-2.amazonaws.com/sample-dotnet-app .

  build:
    commands:    
      - docker tag sample-dotnet-app:latest 344101797155.dkr.ecr.us-west-2.amazonaws.com/sample-dotnet-app:latest
      - docker push 344101797155.dkr.ecr.us-west-2.amazonaws.com/sample-dotnet-app

  post_build:
    commands:
      - echo Deploying to Kubernetes...
      - kubectl apply -f deployment.yaml
